@startuml
title Plato : Get event ANNEXE_DOCUMENT_ADDED from Autocontrol

box "Autocontrol Services" #LightBlue
participant Autocontrol
participant AutocontrolProxy
database AutocontrolProxyDatabase
end box

box "Plato Services" #f2d9a7
database SharedGridFsDB
participant PlatoBackoffice
participant PlatoOutBox
database "PlatoBackoffice DataBase"
end box
Autocontrol <- AutocontrolProxy: getEvent(lastToken)
Autocontrol -> AutocontrolProxy: event notification add annexe
Autocontrol <- AutocontrolProxy: getDocument(href)
Autocontrol <- AutocontrolProxy: getApbNumber(dossierNumber)
AutocontrolProxy -> SharedGridFsDB: saveDocument(file)
AutocontrolProxy -> AutocontrolProxyDatabase: saveCommand(RECEIVED)

AutocontrolProxy -> AutocontrolProxyDatabase: update command PROCESSING
AutocontrolProxy -> PlatoBackoffice: addAnnexeToApbNbr(Command) <<convertSendAndReceive()>>


activate AutocontrolProxy
    activate PlatoBackoffice #FFBBBB

    PlatoBackoffice -> "PlatoBackoffice DataBase": createAnnexeDocument(idGridFS)
    PlatoBackoffice -> "PlatoBackoffice DataBase": updatePharmacyWithApbNbr(idAnnexeDocument, apbNbr)
    return ACCEPTED or REJECTED
    deactivate PlatoBackoffice
deactivate AutocontrolProxy
    PlatoOutBox <-- "PlatoBackoffice DataBase" : notify event update pharmacy (if ACCEPTED) (db push)

PlatoOutBox -> AutocontrolProxy: outbox event update

AutocontrolProxy -> AutocontrolProxy : updateCommandProcessed update pharmacy with annexe




@enduml