@startuml
box "External Services" #LightBlue
participant Autocontrol
participant AutocontrolProxy
end box

box "Internal Services" #LightBlue
participant SharedGridFsDB
participant PlatoBackoffice
participant PlatoOutBox
end box
Autocontrol <- AutocontrolProxy: getEvent(lastToken)
Autocontrol -> AutocontrolProxy: event notification add annexe
Autocontrol <- AutocontrolProxy: getDocument(href)
Autocontrol <- AutocontrolProxy: getApbNumber(dossierNumber)
AutocontrolProxy -> SharedGridFsDB: saveDocument(file)
AutocontrolProxy -> PlatoBackoffice: addAnnexeToApbNbr(fileIdGridFS, apbNbr) <<convertSendAndReceive()>>


activate PlatoBackoffice #FFBBBB

PlatoBackoffice -> PlatoBackoffice: createAnnexeDocument(idGridFS)
PlatoBackoffice -> PlatoBackoffice: updatePharmacyWithApbNbr(idAnnexeDocument, apbNbr)

return ACCEPTED or REJECTED

PlatoOutBox <- PlatoBackoffice : receiveNotification update pharmacy (if ACCEPTED)
PlatoOutBox -> AutocontrolProxy: outbox event update pharmacy

AutocontrolProxy -> AutocontrolProxy : updateCommandProcessed update pharmacy with annexe



@enduml